### ISSUE TITLE
Ability to add additional attributes to inside svg element

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [jannicz/ng-svg-icon-sprite#10]
Hi,

first thing thanks for very good library :)
Would it be possible to add some additional property to component svg-icon-sprite which will dynamically add attributes to inner svg element? Right now we are struggling with the fact that unfortunately we need to be compatible with IE11 and it seems that when you tab between input controls svg element also catches focus - one workaround for it is adding tabindex="-1" (in IE11 it seems that only setting focusable to false helps)
[svg issue](https://github.com/PolymerElements/iron-iconset-svg/issues/46 )
what you think?

**Comment by jannicz** [comment]
Lets make sure I understand you right. So the structure is:
```
<svg-icon-sprite>
  <svg> <- affected by tabfocus?
    <use>
      <svg> <- symbol reference (not affected by focus?)
```

- Are you sure that IE11 tabfocus stops on the **outer SVG node** that is generated by ng-svg-icon-sprite?
- Do you use https://github.com/jonathantneal/svg4everybody to polyfil referencing symbols?

Do you expect following structure to solve the issue?
```
<svg-icon-sprite>
  <svg focusable="false">
```

**Comment by AdaskoTheBeAsT** [comment]
Yes exactly this is what helps
minimum code to reproduce that is
```html
<!DOCTYPE html>
<html>

<head>
  <title>IE11 tab focus problem</title>
</head>

<body>
  <input type="text" />
  <svg height="100" width="100">
    <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
  </svg>
  <input type="text" />
</body>

</html>
```

with focusable
```html
<!DOCTYPE html>
<html>

<head>
  <title>IE11 behaves ok</title>
</head>

<body>
  <input type="text" />
  <svg focusable="false" height="100" width="100">
    <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
  </svg>
  <input type="text" />
</body>

</html>
```

with svg-icon-sprite  (IE11 problem)
```html
<!DOCTYPE html>
<html>

<head>
  <title>IE11 tab focus problem</title>
  <script type="text/javascript">
    document.registerElement('svg-icon-sprite');
  </script>
</head>

<body>
  <input type="text" />
  <svg-icon-sprite>
    <svg>
      <use>
        <svg height="100" width="100">
          <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
        </svg>
      </use>
    </svg>
  </svg-icon-sprite>
  <input type="text" />
</body>

</html>
```

with svg-icon-sprite  (IE11 ok)
```html
<!DOCTYPE html>
<html>

<head>
  <title>IE11 behaves ok</title>
  <script type="text/javascript">
    document.registerElement('svg-icon-sprite');
  </script>
</head>

<body>
  <input type="text" />
  <svg-icon-sprite>
    <svg focusable="false">
      <use>
        <svg height="100" width="100">
          <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
        </svg>
      </use>
    </svg>
  </svg-icon-sprite>
  <input type="text" />
</body>

</html>
```

**Comment by jannicz** [comment]
I understand. As this is a really good improvement proposal I will make a
release tonight so you will be able to test it tomorrow morning.

Thanks for the detailed description!

Adam Pluciński <notifications@github.com> schrieb am Do., 25. Okt. 2018,
04:56:

**Comment by AdaskoTheBeAsT** [comment]
Thanks a lot! :1st_place_medal:

**Comment by jannicz** [comment]
Please check if the last example in https://jannicz.github.io/ng-svg-icon-sprite/ is now not focusable in IE11. If so, I will push the changes also to npm. Thanks for your input!

**Comment by AdaskoTheBeAsT** [comment]
all is ok :) thanks
