### ISSUE TITLE
Firefox not working

### ISSUE THREAD

**Issue by Vladislav-Stanic** [jannicz/ng-svg-icon-sprite#15]
Hi, there are some Firefox bugs with the sprite.
You can open your example on https://jannicz.github.io/ng-svg-icon-sprite/ in Firefox 63.0.3 (Linux) and see that icons are different than on Chrome.
I think that you manually have to add viewBox for each icon on <svg-icon-sprite> component, and also preserveAspectRatio to 'xMidYMid meet'.
At least that was my case on my project with same issues, but those things aren't easy to implement on each icon.

Hope to get some new info.

**Comment by jannicz** [comment]
Thank you for taking the time. You are right, the examples did not work correctly in Firefox. I improved the examples so they now work with all browsers constantly, see https://jannicz.github.io/ng-svg-icon-sprite/#viewBox

For your problem i recommend checking following things:

- does your SVG source include a viewBox constantly across all exported files?
- would adding/removing the viewBox help to get better results?

I think that you have to establish one export and include pattern that will work with all your icons, and then scale them via CSS. Doing so you will not have to write width/viewBox attributes for each icon separately.

If you don't have any objection, i will close this issue tomorrow. Thank you!

**Comment by Vladislav-Stanic** [comment]
Thank you for your reply.
Your fix did the job, all works great now. :)
I will have to test it in IE and other browsers to be sure.

Yes, you can close this issue.
Good job.

**Comment by Vladislav-Stanic** [comment]
Thank you for your reply.
Your fix did the job for your examples, but I am having different issues.
I think it is related to the fact that I am receiving svg's with width and height, and If I strip those attributes with your command than it strips width and height from not only svg but from all inside elements, like rect and so on.
I think I will have manually to remove those attributes.

Thank you.
