### ISSUE TITLE
Adding accessible description to SVG element

### ISSUE THREAD

**Issue by certainlyakey** [jannicz/ng-svg-icon-sprite#16]
Hi and thanks for a great package! 

I miss one thing which is the ability to automatically output an accessible text for screen readers etc. in SVGs that the `svg-icon-sprite` component generates. 

1. According to [svg4everybody README](https://github.com/jonathantneal/svg4everybody#readability-and-accessibility), both `title` attribute and `<title>` tag need to be present for cross-device results. At the current version of the package it is possible to add a title attribute with the `[attribute]`
2. According to [this article](https://simplyaccessible.com/article/7-solutions-svgs/), the best solution is to insert a visually hidden text inside the svg element (by using specific styling, [here's an example](https://gist.github.com/mvsde/f74ad9f5e43994478060e5a559f21922)).

It would be nice to have an additional `@Input` to the `svg-icon-sprite` component that would allow to set descriptive text with some method above.

**Comment by jannicz** [comment]
1) According to [svg4everybody](https://github.com/jonathantneal/svg4everybody#readability-and-accessibility) the title tag can be placed inside of the symbol. This means that you add a title to each of your source SVGs and then process them with the provided script ("create-icon-sprite"). It is actually done so in my examples, i.e. [delete-icon](https://raw.githubusercontent.com/jannicz/ng-svg-icon-sprite/master/src/assets/icons/delete_70x70.svg) - it contains a title tag.
Does your screenreader read after implemented this way?
```
<svg title="some title">
  <use xlink:href="assets/sprites/sprite.svg#star_100x100_viewbox">
    #shadow-root
    <svg xmlns="http://www.w3.org/2000/svg" id="star_100x100_viewbox" width="100%" height="100%" viewBox="0 0 100 100"><g>
    <title>Star </title>
    <path stroke-width="1.5" stroke-opacity="null" d=""></path></g>
    </svg>
  </use>
</svg>
```
Or do you need the title tag in between the opening SVG and the USE tag? If yes, please explain why.

2) Your [article](https://simplyaccessible.com/article/7-solutions-svgs/) recommends to place a visually hidden span as a sibling of the SVG (that itself should be aria-hidden=false):
```
<a href="#">
    <svg aria-hidden="true">
        <use></use>
    </svg>
    <span class="visuallyhidden">Close</span>
</a>
```
This is possible with the current package - so nothing i could provide. So method 2 seems to be accessible without me making changes to my package.

If this does not solve you problem, please give me some code examples what markup you would expect to be generated by my package.

**Comment by certainlyakey** [comment]
> Or do you need the title tag in between the opening SVG and the USE tag? If yes, please explain why.

Yes, that would be preferable as compared to having the same `<title>` for every instance of a single icon. One icon can have different meanings in different contexts, therefore we might need to provide different descriptions for different use cases. For example, a simple user icon can be read as "Account", "Person", etc.

> So method 2 seems to be accessible without me making changes to my package.

You're completely right here. 

Still, since screen readers are constantly evolving/changing, it might be nice to have the ability to customise titles inside each `<svg>` tag next to `<use>` because it seems to be more a more standardised feature than the visually-hidden-div method.
