### ISSUE TITLE
Ability to add multiple attributes to SVG element

### ISSUE THREAD

**Issue by certainlyakey** [jannicz/ng-svg-icon-sprite#17]
Currently we can to add a single attribute to the `<svg>` tag with the `[attribute]` input. However it doesn't seem to be possible to add more than one attribute. If I add multiple `[attribute]` inputs to a `svg-icon-sprite` component (let's say i want to get both `focusable="false"` and `aria-hidden="true"`), only the first one works.

Is there a way to add multiple attributes, and if there isn't, could it be something to implement in future versions of ng-svg-icon-sprite?

**Comment by jannicz** [comment]
Yes, i could provide an alternative @Input attribute to pass multiple key/value pairs. I will provide that in the next release.

**Comment by certainlyakey** [comment]
Awesome, looking forward to it!

**Comment by jannicz** [comment]
@certainlyakey , So i created a [feature branch](https://github.com/jannicz/ng-svg-icon-sprite/pull/18) with a solution for #16 and #17. I would wait with merging and publishing to npm until you verify that the new features actually work with your current project.

You can do this by temporary replacing the node_modules folder ng-svg-icon-sprite with the content of the new build:
[ng-svg-icon-sprite.zip](https://github.com/jannicz/ng-svg-icon-sprite/files/2752268/ng-svg-icon-sprite.zip)

Download and unpack the zip file, replace the old files and use the new attributes like:
```
[title]="'Some title text'"
[attribute]="[['title', 'secondary title attribute'], ['focusable', 'false']]"
```

Please tell me if you encountered any issues.

**Comment by certainlyakey** [comment]
Thanks @jannicz! Did some testing, seems like both features work without any problem. Also thanks for the explanation and the links.

**Comment by jannicz** [comment]
@certainlyakey, that you for your input. I very appreciate your feature request as it helped to improve my component. I now published the package on [npm](https://www.npmjs.com/package/ng-svg-icon-sprite), so you can update it in your project json. Thanks again!

**Comment by certainlyakey** [comment]
Thanks a lot @jannicz for implementing my humble suggestions and for doing a great work!
