### ISSUE TITLE
Cache Busting with svg sprite?

### ISSUE THREAD

**Issue by smiles2424** [jannicz/ng-svg-icon-sprite#20]
After rolling out this awesome library, I've encountered an issue around cache busting.

Since I am referencing the sprite (which is a static file) with a normal path in the html template, it does not go through the normal webpack treatment of getting assigned a hash on each build. 

    <svg-icon-sprite [src]="'assets/sprites/sprite.svg#icon-document'"></svg-icon-sprite>

I've found some workarounds that use `require(!!file-loader!<path>)` to get cache busting for my sprite. Only problem is I have to add more boilerplate everywhere I want to use the `<svg-icon-sprite>`. Workaround found here: https://blog.wishtack.com/2018/06/20/unleash-the-power-of-webpack-in-angular/

Is there another way to get cache busting with sprites?

**Comment by jannicz** [comment]
Images (and SVGs) usually have a long caching time. To solve your problem long term, set the headers for filetype SVG to a lower caching time (i.e. 1 week), [read this](https://varvy.com/pagespeed/cache-control.html).

To solve it short term, you can do following (what sadly **is not best practice**):

1) move the base path of your sprite to an environment variable and append a parameter (?123), i.e.
```
environment = {
  spriteBase: 'assets/sprites/sprite.svg?123'
}
```
2) add the base path to **every** component that uses a sprite:
```
import { environment } from '../environments/environment';

export class AnyComponent {
  env = environment;
```

3) and include it in the template via:
`<svg-icon-sprite [src]="env.spriteBase + '#star_100x100'" [width]="'100px'"></svg-icon-sprite>`

The cache will be invalidated. After lowering SVG caching time server side, remove the parameter.

**Comment by smiles2424** [comment]
What are your thoughts on this feature:

We add the ability to configure the IconSpriteModule with the path(s) to sprite(s). Then a new input is added to the sprite much like `src` but that will use the method you describe above to achieve the same result. The new input (maybe multiple depending what makes the most sense) would specify which sprite and which specific icon.

If you think this makes sense to include in the library, I'll be happy to open a PR.

Edit: alternative solution for anyone reading is to create a wrapper component for the `<svg-icon-sprite>` and to perform the logic above

**Comment by jannicz** [comment]
I very much like your idea of splitting the sprite filename and the icon name. As this lib is now used in many projects, it would have to be done backwards-compatible. I fear that adding a new input (or changing the current src input) might break the logic that is used so far.

Based on your suggestion i was thinking of something like:

- to add a service to the svg-icon-sprite module that can be (optionally) injected into the **app.component** (so the host component and the sprite module would share this new service)
- the service contains a `spritePath` setter for the configuration
- the svg-icon-sprite component can read the `spritePath` from the service
- if a spritePath is given, only the icon name would be sufficient as `src` input

The  svg-icon-sprite component could be then used in **both modes**. If a `spritePath` is given, only the icon name would be required as input. Giving also the filename + icon would override the spritePath. Doing so, the combination of single-color and multi-color sprites would still be feasible and the old API would not be broken.

Would that make the cache busting for you easier and solve your problem?

**Comment by smiles2424** [comment]
That would make things much easier for me 👍

**Comment by jannicz** [comment]
As discussed the lib now supports the feature. If you have a chance to test it for cache busting, i would be happy to head your feedback. Thanks for helping improve this lib. Don't forget to give a star.
