### ISSUE TITLE
Angular 7.2.0 Error: Importing IconSpriteModule which does not have an ngModuleDef

### ISSUE THREAD

**Issue by dhodvogner** [jannicz/ng-svg-icon-sprite#24]
Hello!

I get the following error after I included IconSpriteModule to my AppModule

```
main.ts:11 Error: Importing IconSpriteModule which does not have an ngModuleDef
    at core.js:15106
    at Array.forEach (<anonymous>)
    at transitiveScopesFor (core.js:15103)
    at setScopeOnDeclaredComponents (core.js:15040)
    at flushModuleScopingQueueAsMuchAsPossible (core.js:14808)
    at Function.get (core.js:15208)
    at getComponentDef (core.js:1115)
    at verifyDeclarationsHaveDefinitions (core.js:14921)
    at Array.forEach (<anonymous>)
    at verifySemanticsOfNgModuleDef (core.js:14901)
```

Am I doing something wrong? Can someone help me?

**Comment by jannicz** [comment]
I updated my development app also to Angular 7.2 (see feature branch https://github.com/jannicz/ng-svg-icon-sprite/tree/rc-1.6), but i do not encounter any problems. It seems that this issue has nothing to do with the lib itself.

- Which node version do you use? I recommend >8
- Which typescript version do you use?
- Did you try to delete node_modules and reinstall them?

**Comment by dhodvogner** [comment]
@jannicz 
Sorry for the late answer.
We had the IVY rendering engine turned on in the project (for experimental reasons) but I wasn't aware of it. We experienced similar issues with other packages and modules.
Now it turned off and everything is working as expected.

**Comment by jannicz** [comment]
@dhodvogner good to hear. Let me know if there are any trouble. Give a Star if you like!
