### ISSUE TITLE
could the dynamic icon name auto complete by the function forRoot?

### ISSUE THREAD

**Issue by nolest** [jannicz/ng-svg-icon-sprite#25]
when i use like this:

> Step 2: Use the component
> Having a dynamic icon name:
`<svg-icon-sprite [src]="'assets/sprites/sprite.svg#' + iconName"></svg-icon-sprite>`

colud i setting a default sprite path for icons?
`imports: [
  IconSpriteModule.forRoot({ path: 'assets/sprites/sprite.svg' })
]`
and then having a dynamic icon name:
`<svg-icon-sprite [src]="iconName"></svg-icon-sprite>`

when i change iconName , the path did not combine 'assets/sprites/sprite.svg' and iconName, BUT just get the iconName.

**Comment by jannicz** [comment]
@nolest i fixed the bug and published the new version 1.6.1 to npm. Could you please verify that the fix solves the problem and that the lib works as expected in your project. https://www.npmjs.com/package/ng-svg-icon-sprite

**Comment by nolest** [comment]
> @nolest i fixed the bug and published the new version 1.6.1 to npm. Could you please verify that the fix solves the problem and that the lib works as expected in your project. https://www.npmjs.com/package/ng-svg-icon-sprite

It works! The lib helps our project!
Thanks alot!

**Comment by jannicz** [comment]
Good to hear! Don't forget to give a star :-)
