### ISSUE TITLE
Support Angular 8 

### ISSUE THREAD

**Issue by mits87** [jannicz/ng-svg-icon-sprite#26]
Hi, 

can you support Angular 8 as well? 
Now I have: 

```
npm WARN ng-svg-icon-sprite@1.6.0 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-svg-icon-sprite@1.6.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
```

Thx

**Comment by jannicz** [comment]
Yes, i will provide support in the next release soon! Thanks

**Comment by jannicz** [comment]
I updated the lib to use Angular 8 as default. If you are still using it, i would be glad to hear of the warning disappeared. Thank you
