### ISSUE TITLE
Export IconSpriteConfig from module

### ISSUE THREAD

**Issue by glebmachine** [jannicz/ng-svg-icon-sprite#31]
Unable to use DI to provide config(

**Comment by glebmachine** [comment]
PR: https://github.com/jannicz/ng-svg-icon-sprite/pull/32

**Comment by jannicz** [comment]
Thank you for your improvement! I just pushed your proposed changes.

**Comment by lexigren** [comment]
I'm trying to inject config like so:
```

export function iconSpriteConfigFactory() {
  return {
    path: PathUtils.createAbsolutePath('assets/sprites/sprite.svg?v=1')
  };
}

@NgModule({
  imports: [
    IconSpriteModule,
  ],
  providers: [
    {provide: IconSpriteConfig, useFactory: iconSpriteConfigFactory}
  ]
```

But get an error:
**Module not found: Error: Can't resolve 'ng-svg-icon-sprite/lib/icon-sprite-config.model'**
Am I doing something wrong? 

**edit**
Never mind, I used auto import in IDE, had to import like this:
import {IconSpriteModule, IconSpriteConfig} from 'ng-svg-icon-sprite';
