### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by mits87** [jannicz/ng-svg-icon-sprite#34]
Hi, can you add Angular 9 support for this library?

Currently when I'm doing npm install I got: 

> npm WARN ng-svg-icon-sprite@1.7.1 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN ng-svg-icon-sprite@1.7.1 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
> 

thanks a lot.

**Comment by jannicz** [comment]
A version for Angular 9 will come soon ;-)

**Comment by dudendy** [comment]
@jannicz any news about Angular 9 support?

**Comment by jannicz** [comment]
@andkoval ,@mits87, @AdaskoTheBeAsT: i updated the lib to Angular 9. I had some trouble disabling Ivy and NGCC. I would be thankful if anyone of you could confirm that the new published version runs in your project!
Thank you!

**Comment by dudendy** [comment]
> @andkoval ,@mits87, @AdaskoTheBeAsT: i updated the lib to Angular 9. I had some trouble disabling Ivy and NGCC. I would be thankful if anyone of you could confirm that the new published version runs in your project!
> Thank you!

Thanks a lot, I will take a look ASAP
