### ISSUE TITLE
somethin strange with colors

### ISSUE THREAD

**Issue by MariskaS** [jannicz/ng-svg-icon-sprite#37]
![image](https://user-images.githubusercontent.com/5942101/78328088-4b544680-754c-11ea-8f7f-e8e7a7510b56.png)
![image](https://user-images.githubusercontent.com/5942101/78328111-5c04bc80-754c-11ea-9f5c-ed6908dcefee.png)
coronavirus :) ?
I understand that it happened because of SVG, but maybe somebody can help me to understand - why?
link to my SVG https://help.hrupkie.ru/assets/images/svg-icons/girl.svg

**Comment by sbala69gmail** [comment]
Hi @MariskaS ,

Maybe this is helping you.

If you want to overwrite the color add 'svg2sprite sourcefolder distinationFile --stripAttrs fill --stripAttrs stroke --stripAttrs id'

Else just use `svg2sprite sourcefolder distinationFile`

**Comment by jannicz** [comment]
@MariskaS, is the issue solved? If yes, i will close this Issue...

**Comment by MariskaS** [comment]
> @MariskaS, is the issue solved? If yes, I will close this Issue...

Hey) actually not(the first time I do not correctly understand @sbala69gmail .
I can send you the video with a problem and SVG if you want it) It Looks like this SVG generator cannot work with pictures with different colors. Maybe... I'm not sure) my email marina1988sharmakova@gmail.com, let me know if you wont to see a problem about that I talk

**Comment by MariskaS** [comment]
@jannicz  if I'm removing `--stripAttrs fill --stripAttrs stroke --stripAttrs id` that help's me to save colors of my SVG... I think we can close this issue, it was my mistake
I mean if I have different colors in SVG and I want to save these colors, I need to write:
`"generate:svg-sprite": "svg2sprite ./src/assets/icons ./src/assets/sprites/sprite.svg --stripAttrs id",`

**Comment by jannicz** [comment]
Yes, the IDs are necessary if there are inline styles. I recommend not stripping any attributes if you want to preserve all styles. See here https://github.com/jannicz/ng-svg-icon-sprite#dealing-with-multi-color-svgs-containing-inline-styles

Happy to help
