### ISSUE TITLE
Accessibility attributes issue

### ISSUE THREAD

**Issue by dudendy** [jannicz/ng-svg-icon-sprite#40]
@jannicz First of all thanks for your package, fast response and Angular 9 support :)

I have some issue with dynamic accessibility attributes.
1. It's okay that `ng-reflect-attribute` is cropped?
2. Video should describe the issue - https://www.loom.com/share/28dbd121a453454bb14d9ba297c539aa . `aria-labelledby` updates only after page reload.

Do you have any suggestions maybe?

My icon template: 
```
<svg-icon-sprite
  [src]="'logo'"
  [width]="'109px'"
  [height]="'13px'"
  [classes]="'font-color-light'"
  [attribute]="[['aria-labelledby', 'ticket_search_page.egyjegy_logo_grey.alt' | translate], ['role', 'img']]">
</svg-icon-sprite>
```

**Comment by jannicz** [comment]
It might have to do with Ivy/Ngcc. While porting to Angular 9 I had to disable Ivy (this is a requirement for pre-rendered libs). While doing so, I came across an article that described problems with internationalization. First, lets find out if this is the case here.

Try not to do the translation via a pipe but via a variable that is already defined (i.e. inside the component). Is it helping?

**Comment by dudendy** [comment]
@jannicz I tried to use variable for attribute but have no success. `ng-reflect-attribute` updating on language change for both `svg-icon-sprite` and `svg` inside, but `aria-labelledby` on svg doesn't updating.

**Comment by jannicz** [comment]
I noticed that you use aria-labelledby not the right way. The correct solution works following:

- aria-labelledby's value is a reference to an id (it should not be a text)
- there is a span with the label holding the id (id="label123")
- you translate the span's label, the id stays the same

See: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

If you have no objections I will close this issue by tomorrow

**Comment by dudendy** [comment]
@jannicz You're right about `aria-labelledby`, but the main issue is still that any attribute doesn't update dynamically and my translate pipe doesn't work.

I changed `aria-labelledby` to `aria-label` that's not required id reference, and still no success.

**Comment by jannicz** [comment]
So i don't think that a pipe inside of the property string will work. Last thing you can try:
`[attribute]="wholeArrayAsVariable"`
Put the whole Array as a variable. I don't think this is an issue with the library but rather a limitation how Angular's change detection works. If Angular does not pass your updated string as a Change event, my lib won't be able to do anything about it. You need to find an alternative solution. I recommend referencing the span via id.

**Comment by dudendy** [comment]
ok, thanks for support, close the issue.
