### ISSUE TITLE
Support for version 10?

### ISSUE THREAD

**Issue by ahmadalfy** [jannicz/ng-svg-icon-sprite#45]
Angular 10 is the latest LTS version. I don't know if ng-svg-icon-sprite is currently compatible with it or not

**Comment by jannicz** [comment]
A version for Angular 10 is on its way, release soon. Thank you for using!

**Comment by ikurennyi** [comment]
Hello! Any progress with Angular 10?

**Comment by jannicz** [comment]
I just released version 1.9.0 with Angular 10 support on NPM (https://www.npmjs.com/package/ng-svg-icon-sprite). Please check if it works with your project and create a new issue if any occurs.

Thank you for using!

**Comment by ahmadalfy** [comment]
Thank you so much!
