### ISSUE TITLE
Support for IE 11 with "compilerOptions" target = es5

### ISSUE THREAD

**Issue by Shustoff** [jannicz/ng-svg-icon-sprite#48]
Now I have an error, after run ng serve (Angular 9)

```
Compiling ng-svg-icon-sprite : module as esm5

Warning: Invalid constructor parameter decorator in /node_modules/ng-svg-icon-sprite/fesm2015/ng-svg-icon-sprite.js:
 () => [
    { type: IconSpriteConfig, decorators: [{ type: Optional }] }
]

Error: Error on worker #2: Error: getInternalNameOfClass() called on a non-ES5 class: expected IconSpriteService to have an inner class declaration
```

Change target from es5 to es2015 won't work for IE11

**Comment by jannicz** [comment]
You cannot use ng-svg-icon-sprite version 1.9.x in Angular 9. You have to use the previous version 1.8.x instead. See compatibility https://github.com/jannicz/ng-svg-icon-sprite#compatibility 

Is this hereby solved?

**Comment by Shustoff** [comment]
Yes, it works! Thanks.
