### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by felixwahner** [jannicz/ng-svg-icon-sprite#50]
Currently, when trying to do a `npm install` inside my project it fails (using node v15). That's because there is a hard dependency to angular 10 in the package.json.

I would be really happy if you could test and migrate to angular 11!

Regards
Felix

**Comment by jannicz** [comment]
@felixwahner, yes an Angular 11 version is on its way

**Comment by jannicz** [comment]
@felixwahner please let me know if there are any issues with the version for Angular 11
