### ISSUE TITLE
StaticInjectorError in angular 6.0.4

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [jannicz/ng-svg-icon-sprite#6]
ng-svg-icon-sprite works with angular 6.0.3
unfortunately in 6.0.4 there is an error
ERROR Error: StaticInjectorError[ViewContainerRef]: 
  StaticInjectorError[ViewContainerRef]: 
 NullInjectorError: No provider for ViewContainerRef!

Could you please check?

**Comment by jannicz** [comment]
I created a feature-branch https://github.com/jannicz/ng-svg-icon-sprite/tree/angular-6-upgrade where I performed the update to Angular 6.0.4 to prove the compatibility with this version. No error occurred.

Neither does this component use [ViewContainerRef]. Why do you think this is cased by the icon-sprites?

Can this issue by closed?

**Comment by AdaskoTheBeAsT** [comment]
Sorry it seems false alarm - I encountered that issue after upgrading angular from some previous version - as I have few more libs in project I will need to put more effort into finding what exactly happened.
Issue can be closed.
