### ISSUE TITLE
Upgrade angular to 13

### ISSUE THREAD

**Issue by rvab** [jannicz/ng-svg-icon-sprite#74]
I am upgrading my project from angular 12 to angular 13. I keep getting the error(attached is the screenshot of it). I don't want to use `--force`. Any timelines on how soon I can expect your library to upgrade from angular 12 to angular 13
![Screenshot 2022-03-03 at 1 26 14 PM](https://user-images.githubusercontent.com/11194384/156521167-e0060a0b-31bd-4f4c-b378-feb06335c9c0.png)

**Comment by zeljkoantich** [comment]
Yeah, unfortunately the `IconSpriteModule` won't work in Angular 13 projects.

I'm getting: _core.mjs:1130 Uncaught Error: Type IconSpriteModule does not have 'ɵmod' property._

**Comment by rvab** [comment]
When can I expect the fix for this?

**Comment by abhishek1234321** [comment]
> Yeah, unfortunately the `IconSpriteModule` won't work in Angular 13 projects.
> 
> I'm getting: _core.mjs:1130 Uncaught Error: Type IconSpriteModule does not have 'ɵmod' property._

I have put a PR to upgrade to Angular 14 https://github.com/jannicz/ng-svg-icon-sprite/pull/78, hopefully, @jannicz will review and merge

**Comment by jannicz** [comment]
@abhishek1234321 Thanks for putting the PR. I will have a look today. @zeljkoantich @rvab sorry for the long wait... solution is coming

**Comment by jannicz** [comment]
@abhishek1234321 almost done, do you have an idea how following thing could be fixes? See https://github.com/jannicz/ng-svg-icon-sprite/pull/79

**Comment by jannicz** [comment]
Done and published to npm. Please open a new issue if problems occur with the new build! Many thanks to the supporters! 👌👍😘
