### ISSUE TITLE
error - module not found

### ISSUE THREAD

**Issue by axrl** [jannicz/ng-svg-icon-sprite#95]
After updating to version 1.13.1, an error appeared that the module "ng-svg-icon-sprite" or associated type declarations.ts (2307) could not be found.
Judging by what was loaded into the package folder from npm, the build artifacts were published incorrectly (source code instead of build from dist folder)

**Comment by jannicz** [comment]
OK, i am looking into it. Thanks for checking...

**Comment by jannicz** [comment]
@axrl you were right, i published from the wrong folder. I had to bump the bugfix version in order to publish again, please check the new [package](https://www.npmjs.com/package/ng-svg-icon-sprite/v/1.13.2?activeTab=code) and tell me if that worked!

Thanks so much for contributing!

**Comment by axrl** [comment]
@jannicz  Yes, everything is ok now. Thanks for the quick response)
