### ISSUE TITLE
Incompatible with Angular 17

### ISSUE THREAD

**Issue by Masinac** [jannicz/ng-svg-icon-sprite#98]
`npm ERR! Found: @angular/common@17.0.8

npm ERR! node_modules/@angular/common

npm ERR!   @angular/common@"^17.0.2" from the root project

npm ERR! 

npm ERR! Could not resolve dependency:

npm ERR! peer @angular/common@"^16.0.0" from ng-svg-icon-sprite@1.13.2

npm ERR! node_modules/ng-svg-icon-sprite

npm ERR!   ng-svg-icon-sprite@"1.13.2" from the root project
`

**Comment by jannicz** [comment]
Work in [progress](https://github.com/jannicz/ng-svg-icon-sprite/pull/102)

**Comment by jannicz** [comment]
Done, please check https://www.npmjs.com/package/ng-svg-icon-sprite/v/1.14.0
